### ISSUE TITLE
Choosing landing page

### ISSUE THREAD

**Issue by Duckbilled** [pluja/Parasitter#75]
It would be great to choose the landing screen of yotter. I mostly use Yotter for youtube and the twitter section is just a “nice to have” for me, yet others might prefer the twitter part as their landing page.

**Comment by pluja** [comment]
One of the main reasons for the decision on having a "landing" page where you can choose your platform was that. Also, the landing page where you choose is very lightweight so it loads very smoothly on low-end devices and connections. 

If, for example, the Twitter page was the 'landing' it would take several seconds to load leading to a not-good user welcome - the page would take very long since the user login.

Having a lightwieght landing is a solution for this. Users login and the landing loads in less than a second plus they get to choose their platform.

Maybe for the REACT web-app this could be a good feature.
